-- MySQL Script generated by MySQL Workbench
-- 01/06/20 10:18:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mvc_final
-- -----------------------------------------------------
DROP DATABASE IF EXISTS mvc_final;
CREATE DATABASE IF NOT EXISTS mvc_final;
-- -----------------------------------------------------
-- Schema mvc_final
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mvc_final` DEFAULT CHARACTER SET utf8 ;
USE `mvc_final` ;

-- -----------------------------------------------------
-- Table `mvc_final`.`Employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mvc_final`.`Employees` ;

CREATE TABLE IF NOT EXISTS `mvc_final`.`Employees` (
  `emp_id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  `province` VARCHAR(45) NULL,
  `position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`emp_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mvc_final`.`Employees`
-- -----------------------------------------------------
START TRANSACTION;
USE `mvc_final`;
INSERT INTO `mvc_final`.`Employees` (`emp_id`, `firstname`, `lastname`, `email`, `tel`, `province`, `position`) VALUES (1, 'Rith', 'Nhel', 'parongnhel@gmail.com', '0968682257', 'Battambang', 'WEP trainer');
INSERT INTO `mvc_final`.`Employees` (`emp_id`, `firstname`, `lastname`, `email`, `tel`, `province`, `position`) VALUES (2, 'Rady', 'Y', 'rady.y@gmail.com', NULL, 'Banteay Meanchey', 'WEP trainer');
INSERT INTO `mvc_final`.`Employees` (`emp_id`, `firstname`, `lastname`, `email`, `tel`, `province`, `position`) VALUES (3, 'Savoeurn', 'CHORCH', 'savoeurn.chorch@gmail.com', NULL, 'Battambang', 'SNA trainer');
INSERT INTO `mvc_final`.`Employees` (`emp_id`, `firstname`, `lastname`, `email`, `tel`, `province`, `position`) VALUES (4, 'Thalay', 'SOENG', 'thalay.soeng@gmail.com', NULL, 'Kompong Cham', 'Human Resource Manager');

COMMIT;

